#version 400 core
#define PI 3.14159265359

layout(triangles, equal_spacing, ccw) in;

const int MAX_CASCADE_LEVEL = 8;

in vec3 tc_Pos[];
in vec3 tc_Normal[];
in vec4 tc_Color[];
flat in float tc_min_edge_length[];
in vec3 tc_center[];
in mat4 tc_LightSpacePos0[];
in mat4 tc_LightSpacePos1[];
// in float tc_clipspace_z[];
flat in int tc_Visible[];
flat in int tc_isTriangle[];
flat in float tc_VertexTypeRounded[];
flat in int tc_ovm_halfface_id[];
in vec4 tc_S_c[];

out vec3 v_Pos;
out vec3 v_Normal;
out vec4 v_Color;
out mat4 v_LightSpacePos0;
out mat4 v_LightSpacePos1;
// out float v_clipspace_z;
flat out int v_Visible;
flat out int v_isTriangle;
flat out float v_VertexTypeRounded;
flat out int v_tesInnerTri;

// necessary for calculating bezier mesh face normals
uniform mat4 u_transform;
uniform mat4 u_light_projection[MAX_CASCADE_LEVEL];
uniform mat4 u_light_view[MAX_CASCADE_LEVEL];
uniform mat4 u_light_transform;
uniform float u_cell_size;
uniform bool u_rounding;
uniform float u_rounding_size;
uniform float u_average_cell_size;
// uniform mat4 u_view;
// uniform vec3 u_cam_pos;

// uniform bool u_draw_wireframe;

// uniforms for bezier meshes
uniform bool u_is_bezier_mesh;
uniform int u_bezier_degree;

// use texture buffer for control points
uniform samplerBuffer u_control_points_tb;

const float EDGE_FACTOR = 1.0 / sqrt(2.0);
const float CORNER_FACTOR = sqrt(2.0);

// a maximum bezier degree needs to be set because the De Casteljau algorithm 
// needs an array and GLSL only supports local arrays with static sizes
#define MAX_BEZIER_DEGREE 7
#define MAX_CPS_PER_TRI (MAX_BEZIER_DEGREE+1)*(MAX_BEZIER_DEGREE+2)/2

#define CP_2D_INDEX_TO_1D(i2, i1, m) (((m)+1)*((m)+2)/2 - ((m)-(i2)+1)*((m)-(i2)+2)/2 + (i1))

int cp_2d_index_to_1d(int i2, int i1, int m)
{
    return (((m)+1)*((m)+2)/2 - ((m)-(i2)+1)*((m)-(i2)+2)/2 + (i1));
}

void de_casteljau_2(inout vec3 control_points[MAX_CPS_PER_TRI], int m, float x, float y, float z, int steps)
{
    // Analogous to the De Casteljau algorithm for bezier curves evaluate the 
    // bezier triangle of the current face.
    int cur_m = m;
    for(int s = m; s > m-steps; s--) 
    {
        for(int i2 = 0; i2 < cur_m; i2++) 
        {
            for(int i1 = 0; i1 < cur_m-i2; i1++) 
            {
                int next_i = cp_2d_index_to_1d(i2, i1, cur_m-1);

                int i_1D = cp_2d_index_to_1d(i2,   i1,   cur_m);
                control_points[next_i] =  x*control_points[i_1D];

                i_1D = cp_2d_index_to_1d(i2+1,   i1,   cur_m);
                control_points[next_i] += y*control_points[i_1D];

                i_1D = cp_2d_index_to_1d(i2,   i1+1,   cur_m);
                control_points[next_i] += z*control_points[i_1D];
            }
        }
        cur_m--;
    }
}

void copy_control_points(inout vec3 dest[MAX_CPS_PER_TRI], int control_points_offset, int m)
{
    // Copy control points into dest which holds the temporary values for the
    // de Casteljau algorithm.
    int num_tri_cps = (m+2)*(m+1)/2;
    for(int i = 0; i < num_tri_cps; i++) {
        dest[i] = texelFetch(u_control_points_tb, control_points_offset + i).xyz;
    }
}

float get_shrink_factor(float angle, float dist) {
    float half_angle = angle * 0.5;
    return dist * (1.0 / cos(half_angle) - tan(half_angle));
}

int get_closest_corner_index(vec3 coords)
{
    return coords.x > coords.y ? coords.x > coords.z ? 0 : 2 : coords.y > coords.z ? 1 : 2;
}

void main()
{
    // barycentric coordinates of current triangle
    float x = gl_TessCoord.x;
    float y = gl_TessCoord.y;
    float z = gl_TessCoord.z;

    if(u_is_bezier_mesh)
    {
        // if the mesh is a bezier mesh evaluate the bezier triangle of the
        // current face for the given barycentric coordinates (x, y, z)
        

        // m is the bezier mesh degree (often used in papers)
        int m = u_bezier_degree;
        int ovm_hf_id = tc_ovm_halfface_id[0];
        int control_points_offset = (ovm_hf_id/2)*(m+2)*(m+1)/2;
        vec3 control_points[MAX_CPS_PER_TRI];
        
        // copy control points from texture buffer into local array 
        // so that it can be modified by the de casteljau algorithm
        copy_control_points(control_points, control_points_offset, m);

        // execute m-1 steps of the de casteljau algorithm
        de_casteljau_2(control_points, m, x, y, z, m-1);

        // Calculate normal of point on bézier triangle.
        // The three points generated by the decasteljau algorithm are the
        // tangent of the point of the bézier triangle at (x,y,z).
        // The normal of this tangent triangle is the normal of the point.
        vec3 a = control_points[cp_2d_index_to_1d(0, 0, 1)];
        vec3 b = control_points[cp_2d_index_to_1d(0, 1, 1)];
        vec3 c = control_points[cp_2d_index_to_1d(1, 0, 1)];
        v_Normal = mat3(transpose(inverse(u_transform))) * cross(c - a, b - a);

        // Obtain the final position by doing the last step of linear interpolation
        // of the de casteljau algorithm.
        v_Pos  = control_points[cp_2d_index_to_1d(0, 0, 1)]*x;
        v_Pos += control_points[cp_2d_index_to_1d(1, 0, 1)]*y;
        v_Pos += control_points[cp_2d_index_to_1d(0, 1, 1)]*z;
        
        // Perform Cell sizing.
        vec3 pos = tc_center[0] + (v_Pos - tc_center[0]) * u_cell_size;
        
        v_Pos = vec3(u_transform * vec4(pos, 1.0));


        // Do not render inner tessellated triangled in wireframe mode.
        // For a inner triangle no barycentric coordinate is 0.
        v_tesInnerTri = int(ceil(min(min(x, y), z)));
    
        // Casced Shaowmap for Bézier meshes.
        // Cascaded Shadowmap (loops do not work here, we need to unroll the loop to compile this)
        mat4 light_space_mat = u_light_projection[0] * u_light_view[0] * u_light_transform;
        v_LightSpacePos0[0] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[1] * u_light_view[1] * u_light_transform;
        v_LightSpacePos0[1] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[2] * u_light_view[2] * u_light_transform;
        v_LightSpacePos0[2] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[3] * u_light_view[3] * u_light_transform;
        v_LightSpacePos0[3] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[4] * u_light_view[4] * u_light_transform;
        v_LightSpacePos1[0] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[5] * u_light_view[5] * u_light_transform;
        v_LightSpacePos1[1] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[6] * u_light_view[6] * u_light_transform;
        v_LightSpacePos1[2] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[7] * u_light_view[7] * u_light_transform;
        v_LightSpacePos1[3] = light_space_mat * vec4(pos, 1.0);
    }
    else
    {

        v_tesInnerTri = 0;
        v_LightSpacePos0  = tc_LightSpacePos0[0] *x + tc_LightSpacePos0[1] *y + tc_LightSpacePos0[2] *z;
        v_LightSpacePos1  = tc_LightSpacePos1[0] *x + tc_LightSpacePos1[1] *y + tc_LightSpacePos1[2] *z;

        v_Pos    = tc_Pos[0]    * x + tc_Pos[1]    * y + tc_Pos[2]    * z;
        v_Normal = tc_Normal[0] * x + tc_Normal[1] * y + tc_Normal[2] * z;

        float r = u_rounding_size * u_average_cell_size;//min(u_rounding_size, s_c.w * 0.3);
        if (r > 0.0)
        {
            const ivec2[3] lookup = ivec2[](
                ivec2(1, 2),
                ivec2(0, 2),
                ivec2(0, 1)
            );
            vec3 tri_normal = v_Normal;

            int corner_index = get_closest_corner_index(gl_TessCoord.xyz);
            vec3 corner_pos = tc_Pos[corner_index];
            bool is_corner = corner_pos.x == v_Pos.x && corner_pos.y == v_Pos.y && corner_pos.z == v_Pos.z;
            bool is_edge = gl_TessCoord.x == 0.0 || gl_TessCoord.y == 0.0 || gl_TessCoord.z == 0.0;
            vec4 s_c = tc_S_c[corner_index];

            vec3 p_c = corner_pos + r * s_c.xyz;
            vec3 p = p_c + r * tri_normal;
            float l = length(corner_pos - p);

            vec3 opposite_of_corner = (tc_Pos[lookup[corner_index].x] + tc_Pos[lookup[corner_index].y]) * 0.5;
            float denom = length(opposite_of_corner - corner_pos);
            float scale = l / denom;

            v_Pos += (corner_pos - v_Pos) * (1.0 - scale);
            v_Normal = normalize(v_Pos - p_c);
            // reproject inner vertices onto the original triangle, so the cell does not shrink
            if (!is_edge && !is_corner)
            {
                v_Normal = tri_normal;
            }
            else
            {
                v_Pos = p_c + r * (4.0 / 3.0) * v_Normal;
            }
        }
    }

    // in any case use the values of vertex shader for these values 
    v_Color           = tc_Color[0]          *x + tc_Color[1]          *y + tc_Color[2]          *z;
    // // v_clipspace_z     = tc_clipspace_z[0]    *x + tc_clipspace_z[1]    *y + tc_clipspace_z[2]    *z;
    v_Visible         = tc_Visible[1]        ; // flat
    v_isTriangle      = tc_isTriangle[1]     ; // flat
    v_VertexTypeRounded=tc_VertexTypeRounded[0] * x + tc_VertexTypeRounded[1] * y + tc_VertexTypeRounded[2] * z;
}