#version 400 core
#define PI 3.14159265359

layout(triangles, equal_spacing, ccw) in;

const int MAX_CASCADE_LEVEL = 8;

in vec3 tc_Pos[];
in vec3 tc_Normal[];
in vec4 tc_Color[];
flat in float tc_min_edge_length[];
in vec3 tc_center[];
in mat4 tc_LightSpacePos0[];
in mat4 tc_LightSpacePos1[];
// in float tc_clipspace_z[];
flat in int tc_Visible[];
flat in int tc_isTriangle[];
flat in float tc_VertexTypeRounded[];
flat in int tc_ovm_halfface_id[];

out vec3 v_pos;
out vec3 v_normal;
out vec4 v_color;
out vec2 v_uv;
// out float v_clipspace_z;
flat out int v_visible;
flat out int v_isTriangle;
flat out float v_VertexTypeRounded;
flat out int v_tesInnerTri;

// necessary for calculating bezier mesh face normals
uniform mat4 u_transform;
uniform mat4 u_view;
uniform mat4 u_projection;
uniform mat4 u_light_projection[MAX_CASCADE_LEVEL];
uniform mat4 u_light_view[MAX_CASCADE_LEVEL];
uniform mat4 u_light_transform;
uniform float u_cell_size;
uniform bool u_rounding;
uniform float u_rounding_size;
uniform float u_average_cell_size;
// uniform mat4 u_view;
// uniform vec3 u_cam_pos;

// uniform bool u_draw_wireframe;

// uniforms for bezier meshes
uniform bool u_is_bezier_mesh;
uniform int u_bezier_degree;

// use texture buffer for control points
uniform samplerBuffer u_control_points_tb;

const float EDGE_FACTOR = 1.0 / sqrt(2.0);
const float CORNER_FACTOR = sqrt(2.0);

// a maximum bezier degree needs to be set because the De Casteljau algorithm
// needs an array and GLSL only supports local arrays with static sizes
#define MAX_BEZIER_DEGREE 7
#define MAX_CPS_PER_TRI (MAX_BEZIER_DEGREE+1)*(MAX_BEZIER_DEGREE+2)/2

#define CP_2D_INDEX_TO_1D(i2, i1, m) (((m)+1)*((m)+2)/2 - ((m)-(i2)+1)*((m)-(i2)+2)/2 + (i1))

int cp_2d_index_to_1d(int i2, int i1, int m)
{
    return (((m)+1)*((m)+2)/2 - ((m)-(i2)+1)*((m)-(i2)+2)/2 + (i1));
}

void de_casteljau_2(inout vec3 control_points[MAX_CPS_PER_TRI], int m, float x, float y, float z, int steps)
{
    // Analogous to the De Casteljau algorithm for bezier curves evaluate the 
    // bezier triangle of the current face.
    int cur_m = m;
    for(int s = m; s > m-steps; s--) 
    {
        for(int i2 = 0; i2 < cur_m; i2++) 
        {
            for(int i1 = 0; i1 < cur_m-i2; i1++) 
            {
                int next_i = cp_2d_index_to_1d(i2, i1, cur_m-1);

                int i_1D = cp_2d_index_to_1d(i2,   i1,   cur_m);
                control_points[next_i] =  x*control_points[i_1D];

                i_1D = cp_2d_index_to_1d(i2+1,   i1,   cur_m);
                control_points[next_i] += y*control_points[i_1D];

                i_1D = cp_2d_index_to_1d(i2,   i1+1,   cur_m);
                control_points[next_i] += z*control_points[i_1D];
            }
        }
        cur_m--;
    }
}

void copy_control_points(inout vec3 dest[MAX_CPS_PER_TRI], int control_points_offset, int m)
{
    // Copy control points into dest which holds the temporary values for the
    // de Casteljau algorithm.
    int num_tri_cps = (m+2)*(m+1)/2;
    for(int i = 0; i < num_tri_cps; i++) {
        dest[i] = texelFetch(u_control_points_tb, control_points_offset + i).xyz;
    }
}

float get_shrink_factor(float angle, float dist) {
    float half_angle = angle * 0.5;
    return dist * (1.0 / cos(half_angle) - tan(half_angle));
}

void main()
{
    // barycentric coordinates of current triangle
    float x = gl_TessCoord.x;
    float y = gl_TessCoord.y;
    float z = gl_TessCoord.z;

    if(u_is_bezier_mesh)
    {
        // if the mesh is a bezier mesh evaluate the bezier triangle of the
        // current face for the given barycentric coordinates (x, y, z)
        

        // m is the bezier mesh degree (often used in papers)
        int m = u_bezier_degree;
        int ovm_hf_id = tc_ovm_halfface_id[0];
        int control_points_offset = (ovm_hf_id/2)*(m+2)*(m+1)/2;
        vec3 control_points[MAX_CPS_PER_TRI];
        
        // copy control points from texture buffer into local array 
        // so that it can be modified by the de casteljau algorithm
        copy_control_points(control_points, control_points_offset, m);

        // execute m-1 steps of the de casteljau algorithm
        de_casteljau_2(control_points, m, x, y, z, m-1);

        // Calculate normal of point on bézier triangle.
        // The three points generated by the decasteljau algorithm are the
        // tangent of the point of the bézier triangle at (x,y,z).
        // The normal of this tangent triangle is the normal of the point.
        vec3 a = control_points[cp_2d_index_to_1d(0, 0, 1)];
        vec3 b = control_points[cp_2d_index_to_1d(0, 1, 1)];
        vec3 c = control_points[cp_2d_index_to_1d(1, 0, 1)];
        v_normal = mat3(transpose(inverse(u_transform))) * cross(c - a, b - a);

        // Obtain the final position by doing the last step of linear interpolation
        // of the de casteljau algorithm.
        v_pos  = control_points[cp_2d_index_to_1d(0, 0, 1)]*x;
        v_pos += control_points[cp_2d_index_to_1d(1, 0, 1)]*y;
        v_pos += control_points[cp_2d_index_to_1d(0, 1, 1)]*z;
        
        // Perform Cell sizing.
        vec3 pos = tc_center[0] + (v_pos - tc_center[0]) * u_cell_size;


        v_pos = (u_view * u_transform * vec4(v_pos, 1.0)).xyz;
        gl_Position = u_projection * vec4(v_pos, 1.0);

        //v_pos = vec3(u_transform * vec4(pos, 1.0));

        // Do not render inner tessellated triangled in wireframe mode.
        // For a inner triangle no barycentric coordinate is 0.
        v_tesInnerTri = int(ceil(min(min(x, y), z)));
    
        // Casced Shaowmap for Bézier meshes.
        // Cascaded Shadowmap (loops do not work here, we need to unroll the loop to compile this)
        mat4 light_space_mat = u_light_projection[0] * u_light_view[0] * u_light_transform;
        v_LightSpacePos0[0] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[1] * u_light_view[1] * u_light_transform;
        v_LightSpacePos0[1] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[2] * u_light_view[2] * u_light_transform;
        v_LightSpacePos0[2] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[3] * u_light_view[3] * u_light_transform;
        v_LightSpacePos0[3] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[4] * u_light_view[4] * u_light_transform;
        v_LightSpacePos1[0] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[5] * u_light_view[5] * u_light_transform;
        v_LightSpacePos1[1] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[6] * u_light_view[6] * u_light_transform;
        v_LightSpacePos1[2] = light_space_mat * vec4(pos, 1.0);
        light_space_mat = u_light_projection[7] * u_light_view[7] * u_light_transform;
        v_LightSpacePos1[3] = light_space_mat * vec4(pos, 1.0);
    }
    else
    {

        v_tesInnerTri = 0;
        v_LightSpacePos0  = tc_LightSpacePos0[0] *x + tc_LightSpacePos0[1] *y + tc_LightSpacePos0[2] *z;
        v_LightSpacePos1  = tc_LightSpacePos1[0] *x + tc_LightSpacePos1[1] *y + tc_LightSpacePos1[2] *z;

        float edge_factor = 0.9;
        float corner_factor = 0.9;

        float r = min(u_rounding_size * u_average_cell_size * 0.3, tc_min_edge_length[1] * 0.3);
        vec3 face_center = tc_Pos[0] * (1.0/3.0) + tc_Pos[1] * (1.0/3.0) + tc_Pos[2] * (1.0/3.0);
        float dihedral_angle = PI / 2.0;

        if((x == 0.0 && y == 0.0) || (y == 0.0 && z == 0.0) || (x == 0.0 && z == 0.0))
        {
            // CORNER VERTICES
            v_pos    = tc_Pos[0]    * x + tc_Pos[1]    * y + tc_Pos[2]    * z;
            v_normal = tc_Normal[0] * x + tc_Normal[1] * y + tc_Normal[2] * z;
            face_center = tc_center[1];
            float dist = CORNER_FACTOR * r;
            vec3 shrink_dir = normalize(face_center - v_pos);
            v_pos += shrink_dir * get_shrink_factor(dihedral_angle, dist);

        }
        else
        {
            // EDGE VERTICES
            v_pos    = tc_Pos[0]    * x + tc_Pos[1]    * y + tc_Pos[2]    * z;
            v_normal = tc_Normal[0] * x + tc_Normal[1] * y + tc_Normal[2] * z;

            float dist = EDGE_FACTOR * r;

            if(x == 0.0)
            {
                if(y > z)
                {
                    vec3 edge_dir = normalize(tc_Pos[2] - tc_Pos[1]);
                    vec3 shrink_dir = normalize(face_center - tc_Pos[1]);
                    v_Pos = tc_Pos[1] + edge_dir * dist + shrink_dir * get_shrink_factor(dihedral_angle, dist);
                }
                else
                {
                    vec3 edge_dir = normalize(tc_Pos[1] - tc_Pos[2]);
                    vec3 shrink_dir = normalize(face_center - tc_Pos[2]);
                    v_pos = tc_Pos[2] + edge_dir * dist + shrink_dir * get_shrink_factor(dihedral_angle, dist);
                }
            }
            else if(y == 0.0)
            {
                if(x > z)
                {
                    vec3 edge_dir = normalize(tc_Pos[2] - tc_Pos[0]);
                    vec3 shrink_dir = normalize(face_center - tc_Pos[0]);
                    v_pos = tc_Pos[0] + edge_dir * dist + shrink_dir * get_shrink_factor(dihedral_angle, dist);
                }
                else
                {
                    vec3 edge_dir = normalize(tc_Pos[0] - tc_Pos[2]);
                    vec3 shrink_dir = normalize(face_center - tc_Pos[2]);
                    v_pos = tc_Pos[2] + edge_dir * dist + shrink_dir * get_shrink_factor(dihedral_angle, dist);
                }
            }
            else if(z == 0.0)
            {
                if(x > y)
                {
                    vec3 edge_dir = normalize(tc_Pos[1] - tc_Pos[0]);
                    vec3 shrink_dir = normalize(face_center - tc_Pos[0]);
                    v_pos = tc_Pos[0] + edge_dir * dist + shrink_dir * get_shrink_factor(dihedral_angle, dist);
                }
                else
                {
                    vec3 edge_dir = normalize(tc_Pos[0] - tc_Pos[1]);
                    vec3 shrink_dir = normalize(face_center - tc_Pos[1]);
                    v_pos = tc_Pos[1] + edge_dir * dist + shrink_dir * get_shrink_factor(dihedral_angle, dist);
                }
            }
            else
            {
                // FACE_VERTICES
                if(x > y && x > z)
                {
                    v_pos = tc_Pos[0] + normalize(face_center - tc_Pos[0]) * r;
                }
                else if(y > z)
                {
                    v_pos = tc_Pos[1] + normalize(face_center - tc_Pos[1]) * r;
                }
                else
                {
                    v_pos = tc_Pos[2] + normalize(face_center - tc_Pos[2]) * r;
                }

            }
        }

    }

    // in any case use the values of vertex shader for these values 
    v_color           = tc_Color[0]          *x + tc_Color[1]          *y + tc_Color[2]          *z;
    // // v_clipspace_z     = tc_clipspace_z[0]    *x + tc_clipspace_z[1]    *y + tc_clipspace_z[2]    *z;
    v_visible         = tc_Visible[1]        ; // flat
    v_isTriangle      = tc_isTriangle[1]     ; // flat
    v_VertexTypeRounded=tc_VertexTypeRounded[0] * x + tc_VertexTypeRounded[1] * y + tc_VertexTypeRounded[2] * z;
}