#version 400 core

layout(triangles, equal_spacing, ccw) in;

in vec4 tc_Pos[];
in vec3 tc_normal[];
flat in int tc_visible[];
flat in int tc_ovm_halfface_id[];
flat in vec3 tc_center[];

out vec3 v_normal;
flat out int v_visible;
out vec3 v_pos;

// necessary for calculating bezier mesh face normals
uniform mat4 u_transform;
uniform mat4 u_view;
uniform mat4 u_projection;
uniform float u_cell_size;
// uniform vec3 u_cam_pos;

// uniform bool u_draw_wireframe;

// uniforms for bezier meshes
uniform bool u_is_bezier_mesh;
uniform int u_bezier_degree;

// use texture buffer for control points
uniform samplerBuffer u_control_points_tb;

// a maximum bezier degree needs to be set because the De Casteljau algorithm 
// needs an array and GLSL only supports local arrays with static sizes
#define MAX_BEZIER_DEGREE 7
#define MAX_CPS_PER_TRI (MAX_BEZIER_DEGREE+1)*(MAX_BEZIER_DEGREE+2)/2

#define CP_2D_INDEX_TO_1D(i2, i1, m) (((m)+1)*((m)+2)/2 - ((m)-(i2)+1)*((m)-(i2)+2)/2 + (i1))

int cp_2d_index_to_1d(int i2, int i1, int m)
{
    return (((m)+1)*((m)+2)/2 - ((m)-(i2)+1)*((m)-(i2)+2)/2 + (i1));
}

void de_casteljau_2(inout vec3 control_points[MAX_CPS_PER_TRI], int m, float x, float y, float z, int steps)
{
    // Analogous to the De Casteljau algorithm for bezier curves evaluate the 
    // bezier triangle of the current face.
    int cur_m = m;
    for(int s = m; s > m-steps; s--) 
    {
        for(int i2 = 0; i2 < cur_m; i2++) 
        {
            for(int i1 = 0; i1 < cur_m-i2; i1++) 
            {
                int next_i = cp_2d_index_to_1d(i2, i1, cur_m-1);

                int i_1D = cp_2d_index_to_1d(i2,   i1,   cur_m);
                control_points[next_i] =  x*control_points[i_1D];

                i_1D = cp_2d_index_to_1d(i2+1,   i1,   cur_m);
                control_points[next_i] += y*control_points[i_1D];

                i_1D = cp_2d_index_to_1d(i2,   i1+1,   cur_m);
                control_points[next_i] += z*control_points[i_1D];
            }
        }
        cur_m--;
    }
}

void copy_control_points(inout vec3 dest[MAX_CPS_PER_TRI], int control_points_offset, int m)
{
    // Copy control points into dest which holds the temporary values for the
    // de Casteljau algorithm.
    int num_tri_cps = (m+2)*(m+1)/2;
    for(int i = 0; i < num_tri_cps; i++) {
        dest[i] = texelFetch(u_control_points_tb, control_points_offset + i).xyz;
    }
}

void main()
{
    // barycentric coordinates of current triangle
    float x = gl_TessCoord.x;
    float y = gl_TessCoord.y;
    float z = gl_TessCoord.z;

    if(u_is_bezier_mesh)
    {
        // if the mesh is a bezier mesh evaluate the bezier triangle of the
        // current face for the given barycentric coordinates (x, y, z)
        

        // m is the bezier mesh degree (often used in papers)
        int m = u_bezier_degree;
        int ovm_hf_id = tc_ovm_halfface_id[0];
        int control_points_offset = (ovm_hf_id/2)*(m+2)*(m+1)/2;
        vec3 control_points[MAX_CPS_PER_TRI];
        
        // copy control points from texture buffer into local array 
        // so that it can be modified by the de casteljau algorithm
        copy_control_points(control_points, control_points_offset, m);

        // execute m-1 steps of the de casteljau algorithm
        de_casteljau_2(control_points, m, x, y, z, m-1);

        // Calculate normal of point on bézier triangle.
        // The three points generated by the decasteljau algorithm are the
        // tangent of the point of the bézier triangle at (x,y,z).
        // The normal of this tangent triangle is the normal of the point.
        vec3 a = control_points[cp_2d_index_to_1d(0, 0, 1)];
        vec3 b = control_points[cp_2d_index_to_1d(0, 1, 1)];
        vec3 c = control_points[cp_2d_index_to_1d(1, 0, 1)];
        v_normal = mat3(transpose(inverse(u_view * u_transform))) * cross(c - a, b - a);

        // Obtain the final position by doing the last step of linear interpolation
        // of the de casteljau algorithm.
        v_pos       = control_points[cp_2d_index_to_1d(0, 0, 1)]*x;
        v_pos      += control_points[cp_2d_index_to_1d(1, 0, 1)]*y;
        v_pos      += control_points[cp_2d_index_to_1d(0, 1, 1)]*z;
        
        // Perform Cell sizing.
        v_pos = tc_center[0] + (v_pos - tc_center[0]) * u_cell_size;

        v_pos = (u_view * u_transform * vec4(v_pos, 1.0)).xyz;
        gl_Position = u_projection * vec4(v_pos, 1.0);
    }
    else
    {
        gl_Position   = tc_Pos[0]            *x + tc_Pos[1]            *y + tc_Pos[2]            *z;
        v_normal      = tc_normal[0]         *x + tc_normal[1]         *y + tc_normal[2]         *z;
        v_pos         = vec3(0.);
    }

    // in any case use the values of vertex shader for these values 
    v_visible         = tc_visible[0]; //flat
}